repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: scorecard

  # A short description of the repository that will show up on GitHub
  description: Security Scorecards - Security health metrics for Open Source

  # A URL with more information about the repository
  homepage: ''

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to enable automated security fixes, or `false` to disable
  # automated security fixes.
  enable_automated_security_fixes: true

  # Either `true` to enable vulnerability alerts, or `false` to disable
  # vulnerability alerts.
  enable_vulnerability_alerts: true

# See https://docs.github.com/en/rest/reference/teams#add-or-update-team-repository-permissions for available options
teams: []
    # The permission to grant the team. Can be one of:
    # * `pull` - can pull, but not push to or administer this repository.
    # * `push` - can pull and push, but not administer this repository.
    # * `admin` - can pull, push and administer this repository.
    # * `maintain` - Recommended for project managers who need to manage the repository without access to sensitive or destructive actions.

# Collaborators: give specific users access to this repository.
# See https://docs.github.com/en/rest/reference/collaborators for available options

# THIS LIST SHOULD ALWAYS MATCH TOP-LEVEL CODEOWNERS
# https://github.com/ossf/scorecard/blob/main/.github/CODEOWNERS

# TODO(owners): For ease of management, this should eventually shift to a
#               defined GitHub team instead of individual usernames
collaborators:
  # Admin
  - name: azeemshaikh38
    permission: admin

  - name: inferno-chromium
    permission: admin

  - name: justaugustus
    permission: admin

  - name: laurentsimon
    permission: admin

  - name: naveensrinivasan
    permission: admin

  - name: oliverchang
    permission: admin

  # Maintain
  - name: olivekl
    permission: maintain

  # Write
  - name: chrismcgehee
    permission: write

  # Triage
  - name: meder
    permission: admin

branches:
  - name: main
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: []
          teams: []
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Prevent merge commits from being pushed to matching branches
      required_linear_history: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: []
        users: []
        teams: []
